import pyodbc

conn = pyodbc.connect('DRIVER=/usr/lib/x86_64-linux-gnu/libssodbcw.so;SERVER=127.0.0.1;PORT=3306;DATABASE=tpcc;UID=root;PWD=root')
cursor = conn.cursor()
cursor.execute('optimize table CUSTOMER full')
cursor.execute('analyze table CUSTOMER')
cursor.execute('optimize table DISTRICT full')
cursor.execute('analyze table DISTRICT')
cursor.execute('optimize table HISTORY full')
cursor.execute('analyze table HISTORY')
cursor.execute('optimize table ITEM full')
cursor.execute('analyze table ITEM')
cursor.execute('optimize table NATION full')
cursor.execute('analyze table NATION')
cursor.execute('optimize table NEW_ORDER full')
cursor.execute('analyze table NEW_ORDER')
cursor.execute('optimize table ORDERS full')
cursor.execute('analyze table ORDERS')
cursor.execute('optimize table ORDER_LINE full')
cursor.execute('analyze table ORDER_LINE')
cursor.execute('optimize table REGION full')
cursor.execute('analyze table REGION')
cursor.execute('optimize table STOCK full')
cursor.execute('analyze table STOCK')
cursor.execute('optimize table SUPPLIER full')
cursor.execute('analyze table SUPPLIER')
cursor.execute('optimize table WAREHOUSE full')
cursor.execute('analyze table WAREHOUSE')
cursor.execute('DROP ALL FROM PLANCACHE')
conn.close()
